# Target specific macros
TARGET = motorEx

TARGET_CPP_SOURCES = \
					 main.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./main.oil

BUILD_MODE = 

# GCC optimisation level
#-Os optimisation for size
#-O1/2/3 optimisation for speed
C_OPTIMISATION_FLAGS = -Os

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include /nxtOSEK/ecrobot/ecrobot++.mak
